### ISSUE TITLE
Error while trying to set in external memory

### ISSUE THREAD

**Issue by eranor** [ZwerOxotnik/m-microcontroller#10]
Hi. While trying to write to the external memory I've got the following error:

![image](https://user-images.githubusercontent.com/471307/90301126-3a262980-de9e-11ea-8119-153b793cfad0.png)

Code:
```
clr
set 11 mem1
set 1 mem@1
```

Placement of modules: 
![image](https://user-images.githubusercontent.com/471307/90301132-490cdc00-de9e-11ea-9a33-426852e4aa7b.png)

Please is this something that currently not supported or a bug?

**Comment by ZwerOxotnik** [comment]
Apparently, it's the case when documentation and mod wasn't obvious with debugging and with RAM modules. Ha... Just add the output signal "RAM module" to the RAM module.

![](https://user-images.githubusercontent.com/16271098/90311528-5eb4ec80-df04-11ea-86b7-000c945f1332.png)

**Comment by eranor** [comment]
I completely glossed over that `clr` would reset those registers too 😅. Thank you for explaining😄
