### ISSUE TITLE
_m-microcontroller__/compiler.lua:287: attempt to index field 'parameters' (a nil value)

### ISSUE THREAD

**Issue by thomasjohn314** [ZwerOxotnik/m-microcontroller#12]
I get:
`_m-microcontroller__/compiler.lua:287: attempt to index field 'parameters' (a nil value)`

When trying to run:
`set mem1 out`

**Comment by ZwerOxotnik** [comment]
Fixed, download new version from https://mods.factorio.com/mod/m-microcontroller/downloads
