### ISSUE TITLE
[FIXED] Editor Mode First Placement Crashes World

### ISSUE THREAD

**Issue by MaxTheMooshroom** [ZwerOxotnik/m-microcontroller#16]
**Describe the bug**
When I place down the world's first microcontroller in editor mode, it crashes the world with the following error (this is the only installed mod, I sanitized to check if it was caused by another mod):
```
The mod MicroController (0.11.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event m-microcontroller::on_built_entity (ID 6)
__m-microcontroller__/control.lua:91: bad argument #1 of 2 to 'ipairs' (table expected, got nil)
stack traceback:
	[C]: in function 'ipairs'
	__m-microcontroller__/control.lua:91: in function <__m-microcontroller__/control.lua:83>
```
If I place one down outside of editor mode first, everything works fine.

**Steps to reproduce**
1. Create a world
2. Enter editor mode
3. Place MicroController

**Expected behavior**
not crashing?

**Comment by ZwerOxotnik** [comment]
Change "Update tick time" to 1 in map settings. I'll fix it a bit later.

**Comment by MaxTheMooshroom** [comment]
apologies, I forgot that I had already set it to 1 so I didn't include it in the bug description.

**Comment by ZwerOxotnik** [comment]
New update should fix it, please, confirm.

**Comment by MaxTheMooshroom** [comment]
Looks like it works, thank you! Read the source change as well, looks very good! I was wondering whether you'd do a bodge fix or a proper patch, was glad to see a proper patch!
